[package]
name = "vienna"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio-util = { version = "0.7.14", features = ["codec"] }
anyhow = "1.0.97"
tokio = { version = "1.44.1", features = ["full"] }
futures-util = { version = "0.3.31", features = ["sink"] }
fastrand = "2.3.0"
